base_config: ./config/
base_expid: DCNv3_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    num_deep_cross_layers: [3, 4, 5]
    num_shallow_cross_layers: [3, 4, 5]
    deep_net_dropout: [0]
    shallow_net_dropout: [0, 0.1, 0.2, 0.3]
