base_config: ./config/
base_expid: DCNv3_ML_1M
dataset_id: ML_1M_7_x1

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    num_deep_cross_layers: [1, 2, 3]
    num_shallow_cross_layers: [1, 2, 3, 4]
    deep_net_dropout: [0.1, 0.2, 0.3]
    shallow_net_dropout: [0.1, 0.2, 0.3]
